name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: sample action
        uses: ./.github/actions/dummy
        with:
          dummy-secrets: ${{ secrets.DUMMY_SECRETS }}
        env:
          DUMMY_SECRETS: ${{ secrets.DUMMY_SECRETS }}